// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface Counter
{
    // Counter
    public String getIdentifier();
    public String getListStyle();
    public String getSeparator();
}
