// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.DOMException;

public interface CSSCharsetRule extends CSSRule
{
    // CSSCharsetRule
    public String getEncoding();
    public void setEncoding(String encoding) throws DOMException;
}
