// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.stylesheets.MediaList;

public interface CSSImportRule extends CSSRule
{
    // CSSImportRule
    public String getHref();
    public MediaList getMedia();
    public void setMedia(String media);
    public CSSStyleSheet getStyleSheet();
}
