// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface CSSIdentifierComponentValue
{
    // CSSIdentifierComponentValue
    public String getIdentifier();
    public void setIdentifier(String identifier);
}
