// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;


public interface CSSNamespaceRule extends CSSRule
{
    // CSSNamespaceRule
    public String getNamespaceURI();
    public String getPrefix();
}
