// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.ObjectArray;

public interface CSSPropertyValueList
{
    // CSSPropertyValueList
    public ObjectArray<CSSValue> getList();
}
