// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface CSSPercentageComponentValue
{
    // CSSPercentageComponentValue
    public float getPercent();
    public void setPercent(float percent);
}
