// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface CSSPageRule extends CSSRule
{
    // CSSPageRule
    public String getSelectorText();
    public void setSelectorText(String selectorText);
    public CSSStyleDeclaration getStyle();
}
