// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface CSSPropertyValue
{
    // CSSPropertyValue
    public String getCssText();
    public void setCssText(String cssText);
}
