// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.ObjectArray;
import com.dragome.w3c.dom.stylesheets.StyleSheet;

public interface CSSStyleSheet extends StyleSheet
{
    // CSSStyleSheet
    public CSSRule getOwnerRule();
    public ObjectArray<CSSRule> getCssRules();
    public int insertRule(String rule, int index);
    public void deleteRule(int index);
}
