// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface CSSValueList extends CSSValue
{
    // CSSValueList
    public int getLength();
    public CSSValue item(int index);
}
