// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.Element;

public interface DocumentCSS
{
    // DocumentCSS
    public CSSStyleDeclaration getOverrideStyle(Element elt, String pseudoElt);
}
