// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

import com.dragome.w3c.dom.DOMException;

public interface DOMImplementationCSS
{
    // DOMImplementationCSS
    public CSSStyleSheet createCSSStyleSheet(String title, String media) throws DOMException;
}
