// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface Rect
{
    // Rect
    public CSSPrimitiveValue getTop();
    public CSSPrimitiveValue getRight();
    public CSSPrimitiveValue getBottom();
    public CSSPrimitiveValue getLeft();
}
