// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.css;

public interface RGBColor
{
    // RGBColor
    public CSSPrimitiveValue getRed();
    public CSSPrimitiveValue getGreen();
    public CSSPrimitiveValue getBlue();
}
