// Generated by esidl 0.4.0.

package org.w3c.dom.html;

public interface CanvasPixelArray
{
    // CanvasPixelArray
    public int getLength();
    public int getElement(int index);
    public void setElement(int index, int value);
}
