// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.traversal;

import com.dragome.w3c.dom.DOMException;
import com.dragome.w3c.dom.Node;

public interface DocumentTraversal
{
    // DocumentTraversal
    public NodeIterator createNodeIterator(Node root, int whatToShow, NodeFilter filter, boolean entityReferenceExpansion) throws DOMException;
    public TreeWalker createTreeWalker(Node root, int whatToShow, NodeFilter filter, boolean entityReferenceExpansion) throws DOMException;
}
