// Generated by esidl 0.4.0.

package org.w3c.dom;

import org.w3c.dom.events.EventTarget;

public interface XMLHttpRequestEventTarget extends EventTarget
{
    // XMLHttpRequestEventTarget
    public EventHandler getOnloadstart();
    public void setOnloadstart(EventHandler onloadstart);
    public EventHandler getOnprogress();
    public void setOnprogress(EventHandler onprogress);
    public EventHandler getOnabort();
    public void setOnabort(EventHandler onabort);
    public EventHandler getOnerror();
    public void setOnerror(EventHandler onerror);
    public EventHandler getOnload();
    public void setOnload(EventHandler onload);
    public EventHandler getOntimeout();
    public void setOntimeout(EventHandler ontimeout);
    public EventHandler getOnloadend();
    public void setOnloadend(EventHandler onloadend);
}
