// Generated by esidl 0.4.0.

package org.w3c.dom;

public interface XMLHttpRequest extends XMLHttpRequestEventTarget
{
    // XMLHttpRequest
    public EventHandler getOnreadystatechange();
    public void setOnreadystatechange(EventHandler onreadystatechange);
    public static final short UNSENT = 0;
    public static final short OPENED = 1;
    public static final short HEADERS_RECEIVED = 2;
    public static final short LOADING = 3;
    public static final short DONE = 4;
    public short getReadyState();
    public void open(String method, String url);
    public void open(String method, String url, boolean async);
    public void open(String method, String url, boolean async, String username);
    public void open(String method, String url, boolean async, String username, String password);
    public void setRequestHeader(String header, String value);
    public int getTimeout();
    public void setTimeout(int timeout);
    public boolean getWithCredentials();
    public void setWithCredentials(boolean withCredentials);
    public XMLHttpRequestUpload getUpload();
    public void send();
    public void send(Object data);
    public void abort();
    public short getStatus();
    public String getStatusText();
    public String getResponseHeader(String header);
    public String getAllResponseHeaders();
    public void overrideMimeType(String mime);
    public String getResponseType();
    public void setResponseType(String responseType);
    public Object getResponse();
    public String getResponseText();
    public Document getResponseXML();
}
