// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.webgl;

public interface WebGLActiveInfo
{
    // WebGLActiveInfo
    public int getSize();
    public int getType();
    public String getName();
}
