/*
 * eventsource.idl
 *
 * Server-Sent Events
 *
 * Original W3C Editor's Draft 28 February 2011:
 *
 *   http://dev.w3.org/html5/eventsource/
 */

module eventsource {

typedef events::EventTarget EventTarget;
typedef html::Function Function;

[Constructor(in DOMString url)]
interface EventSource : EventTarget {
  readonly attribute DOMString url;

  // ready state
  const unsigned short CONNECTING = 0;
  const unsigned short OPEN = 1;
  const unsigned short CLOSED = 2;
  readonly attribute unsigned short readyState;

  // networking
           attribute Function onopen;
           attribute Function onmessage;
           attribute Function onerror;
  void close();
};

};

