/*
 * webnotifications.idl
 *
 * Web Notifications IDL definitions scraped from the W3C specification, revised for esidl.
 *
 * Original W3C Editor's Draft 22 April 2010
 *
 *   http://dev.w3.org/2006/webapi/WebNotifications/publish/
 */

module webnotifications {

typedef events::EventTarget EventTarget;
typedef html::Navigator Navigator;
typedef html::Function Function;
typedef workers::WorkerNavigator WorkerNavigator;

interface Notification : EventTarget {

  void               show();
  void               cancel();
           attribute Function  onclick;
           attribute Function  ondisplay;
           attribute Function  onerror;
           attribute Function  onclose;
           attribute long      replaceId;
           attribute string    dir;
};

interface NotificationCenter {
  // permission values
  const unsigned long      PERMISSION_ALLOWED      = 0;
  const unsigned long      PERMISSION_UNKNOWN      = 1;
  const unsigned long      PERMISSION_DENIED       = 2;

           attribute unsigned long  permissionLevel;
  Notification       createNotification(in DOMString iconUrl, in DOMString title, in DOMString body);
                                        // raises(Exception);
  Notification       createHTMLNotification(in DOMString url);
  void               requestPermission(in Function callback);
                                        // raises(Exception);
};

Navigator implements NotificationCenter;

WorkerNavigator implements NotificationCenter;

[Supplemental] interface NotificationCenter {
  Notification createWebNotification(in DOMString url);
                                        // raises(Exception);
};

};
