// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.typedarray;

public interface DataView_Constructor
{
    // Constructor
    public DataView createInstance(ArrayBuffer buffer);
    public DataView createInstance(ArrayBuffer buffer, int byteOffset);
    public DataView createInstance(ArrayBuffer buffer, int byteOffset, int byteLength);
}
