// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

public interface DocumentType extends Node
{
    // DocumentType
    public String getName();
    public String getPublicId();
    public String getSystemId();
}
