// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

public interface DocumentFragment extends Node
{
    // DocumentFragment
    // NodeSelector
    public Element querySelector(String selectors);
    public NodeList querySelectorAll(String selectors);
}
