// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

public interface DOMSettableTokenList extends DOMTokenList
{
    // DOMSettableTokenList
    public String getValue();
    public void setValue(String value);
}
