// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

public interface DOMStringList
{
    // DOMStringList
    public int getLength();
    public String item(int index);
    public boolean contains(String string);
}
