// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

import com.dragome.w3c.dom.file.Blob;

public interface FormData
{
    // FormData
    public void append(String name, Blob value);
    public void append(String name, String value);
}
