// Generated by esidl 0.4.0.

package com.dragome.w3c.dom;

public interface OctetArray
{
    // OctetArray
    public int getLength();
    public void setLength(int length);
    public byte getElement(int index);
    public void setElement(int index, byte value);
}
