// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.events;

public interface CustomEvent_Constructor
{
    // Constructor
    public CustomEvent createInstance(String type);
    public CustomEvent createInstance(String type, CustomEventInit eventInitDict);
}
