// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.events;

public interface EventInit
{
    // EventInit
    public boolean getBubbles();
    public void setBubbles(boolean bubbles);
    public boolean getCancelable();
    public void setCancelable(boolean cancelable);
}
