// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.events;

public interface Touch
{
    // Touch
    public int getIdentifier();
    public EventTarget getTarget();
    public int getScreenX();
    public int getScreenY();
    public int getClientX();
    public int getClientY();
    public int getPageX();
    public int getPageY();
}
