// Generated by esidl 0.4.0.

package org.w3c.dom.events;

public interface TouchEvent extends UIEvent
{
    // TouchEvent
    public TouchList getTouches();
    public TouchList getTargetTouches();
    public TouchList getChangedTouches();
    public boolean getAltKey();
    public boolean getMetaKey();
    public boolean getCtrlKey();
    public boolean getShiftKey();
}
