// Generated by esidl 0.4.0.

package org.w3c.dom.websocket;

public interface WebSocket_Constructor
{
    // Constructor
    public WebSocket createInstance(String url);
    public WebSocket createInstance(String url, String protocol);
}
