// Generated by esidl 0.4.0.

package org.w3c.dom.websocket;

import org.w3c.dom.events.EventListener;
import org.w3c.dom.events.EventTarget;

public interface WebSocket extends EventTarget
{
    // WebSocket
    public String getURL();
    public static final short CONNECTING = 0;
    public static final short OPEN = 1;
    public static final short CLOSED = 2;
    public short getReadyState();
    public int getBufferedAmount();
    public EventListener getOnopen();
    public void setOnopen(EventListener onopen);
    public EventListener getOnmessage();
    public void setOnmessage(EventListener onmessage);
    public EventListener getOnclose();
    public void setOnclose(EventListener onclose);
    public boolean send(String data);
    public void close();
}
