// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.views;

public interface ClientRect
{
    // ClientRect
    public float getTop();
    public float getRight();
    public float getBottom();
    public float getLeft();
    public float getWidth();
    public float getHeight();
}
