// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.events.Event;

public interface BeforeUnloadEvent extends Event
{
    // BeforeUnloadEvent
    public String getReturnValue();
    public void setReturnValue(String returnValue);
}
