// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.DOMStringList;
import com.dragome.w3c.dom.Element;
import com.dragome.w3c.dom.file.FileList;

public interface DataTransfer
{
    // DataTransfer
    public String getDropEffect();
    public void setDropEffect(String dropEffect);
    public String getEffectAllowed();
    public void setEffectAllowed(String effectAllowed);
    public DataTransferItemList getItems();
    public void setDragImage(Element image, int x, int y);
    public void addElement(Element element);
    public DOMStringList getTypes();
    public String getData(String format);
    public void setData(String format, String data);
    public void clearData();
    public void clearData(String format);
    public FileList getFiles();
}
