// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface External
{
    // External
    public void AddSearchProvider(String engineURL);
    public int IsSearchProviderInstalled(String engineURL);
}
