// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLLegendElement extends HTMLElement
{
    // HTMLLegendElement
    public HTMLFormElement getForm();
    // HTMLLegendElement-22
    public String getAlign();
    public void setAlign(String align);
}
