// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLTableCaptionElement extends HTMLElement
{
    // HTMLTableCaptionElement
    // HTMLTableCaptionElement-11
    public String getAlign();
    public void setAlign(String align);
}
