// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLTableHeaderCellElement extends HTMLTableCellElement
{
    // HTMLTableHeaderCellElement
    public String getScope();
    public void setScope(String scope);
}
