// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLDivElement extends HTMLElement
{
    // HTMLDivElement
    // HTMLDivElement-13
    public String getAlign();
    public void setAlign(String align);
}
