// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLFormControlsCollection extends HTMLCollection
{
    // HTMLFormControlsCollection
    public Object namedItem(String name);
}
