// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface HTMLParamElement extends HTMLElement
{
    // HTMLParamElement
    public String getName();
    public void setName(String name);
    public String getValue();
    public void setValue(String value);
    // HTMLParamElement-30
    public String getType();
    public void setType(String type);
    public String getValueType();
    public void setValueType(String valueType);
}
