// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.DOMStringList;

public interface HTMLPropertiesCollection extends HTMLCollection
{
    // HTMLPropertiesCollection
    public PropertyNodeList namedItem(String name);
    public DOMStringList getNames();
}
