// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface ImageData
{
    // ImageData
    public int getWidth();
    public int getHeight();
    public CanvasPixelArray getData();
}
