// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.ObjectArray;
import com.dragome.w3c.dom.events.Event;

public interface MessageEvent extends Event
{
    // MessageEvent
    public Object getData();
    public String getOrigin();
    public String getLastEventId();
    public Window getSource();
    public ObjectArray<MessagePort> getPorts();
    public void initMessageEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, Object dataArg, String originArg, String lastEventIdArg, Window sourceArg, MessagePort[] portsArg);
}
