// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface NavigatorUserMediaSuccessCallback
{
    // NavigatorUserMediaSuccessCallback
    public void handleEvent(LocalMediaStream stream);
}
