// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface NavigatorUserMediaError
{
    // NavigatorUserMediaError
    public static final short PERMISSION_DENIED = 1;
    public short getCode();
}
