// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.events.Event;

public interface PageTransitionEvent extends Event
{
    // PageTransitionEvent
    public boolean getPersisted();
    public void initPageTransitionEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, boolean persistedArg);
}
