// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface PeerConnection_Constructor
{
    // Constructor
    public PeerConnection createInstance(String configuration, SignalingCallback signalingCallback);
}
