// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

import com.dragome.w3c.dom.NodeList;

public interface PropertyNodeList extends NodeList
{
    // PropertyNodeList
    public Object[] getValues();
}
