// Generated by esidl 0.4.0.

package com.dragome.w3c.dom.html;

public interface WindowModal
{
    // WindowModal
    public Object getDialogArguments();
    public String getReturnValue();
    public void setReturnValue(String returnValue);
}
